/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.menu;

import api.login.ArchivoLogin;
import frontend.gui.CalendarioHaab;
import gui.infonahuales.VentanaInfoNahuales;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelos.objetos.FechaCholqij;
import modelos.objetos.FechaHaab;
import modelos.objetos.Usuario;
import principal.backend.perfil_usuario.Informacion;
import principal.frontend.gui.calendari_cholquij.FrameCalendario;
import principal.frontend.gui.perfil_usuario.FramePerfil;
import principal.ui.EventoDeTiempo;
import principal.ui.LineaDeTiempo;
import principal.ui.RuedaCalendarica;

/**
 *
 * @author luisGonzalez
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Informacion info = new Informacion();
    public final static ImageIcon BG = new ImageIcon("Imagenes/BackGroundMainMenu.jpg");
    private Usuario user;
    private ArchivoLogin archivoLogin = new ArchivoLogin();
    private String fechaStr;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Usuario user) {
        Calendar fecha = new GregorianCalendar();
        String dia = Integer.toString(fecha.get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(fecha.get(Calendar.MONTH) + 1);
        String annio = Integer.toString(fecha.get(Calendar.YEAR));
        fechaStr = annio + "-" + mes + "-" + dia;
        
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);       
        pnlFechas.setBackground(new Color(0, 0, 0, 123));
        setBackground();
        designe();
        escribirFecha();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnlMenu = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCholqij = new javax.swing.JButton();
        panelC2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnHaab = new javax.swing.JButton();
        panelC3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnRuedaCalen = new javax.swing.JButton();
        panelC4 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnLinea = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        CalendarioMayaBTN = new javax.swing.JButton();
        panelC1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        btnNahuales = new javax.swing.JButton();
        panelC5 = new javax.swing.JSeparator();
        pnlFechas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFechaCholquij = new javax.swing.JLabel();
        lblFechaHaab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        pnlMenu.setBackground(new java.awt.Color(1, 1, 1));

        btnPerfil.setBackground(new java.awt.Color(204, 204, 204));
        btnPerfil.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(254, 254, 254));
        btnPerfil.setText("Mi Perfil");
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setRolloverEnabled(false);
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        btnCholqij.setBackground(new java.awt.Color(204, 204, 204));
        btnCholqij.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnCholqij.setForeground(new java.awt.Color(254, 254, 254));
        btnCholqij.setText("Calendario Cholqij");
        btnCholqij.setBorderPainted(false);
        btnCholqij.setContentAreaFilled(false);
        btnCholqij.setRolloverEnabled(false);
        btnCholqij.setVerifyInputWhenFocusTarget(false);
        btnCholqij.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCholqijMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCholqijMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCholqijMouseEntered(evt);
            }
        });
        btnCholqij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCholqijActionPerformed(evt);
            }
        });

        panelC2.setBackground(new java.awt.Color(39, 232, 232));
        panelC2.setForeground(new java.awt.Color(58, 254, 243));
        panelC2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCholqij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelC2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnCholqij, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);

        btnHaab.setBackground(new java.awt.Color(204, 204, 204));
        btnHaab.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnHaab.setForeground(new java.awt.Color(254, 254, 254));
        btnHaab.setText("Calendario Haab");
        btnHaab.setBorderPainted(false);
        btnHaab.setContentAreaFilled(false);
        btnHaab.setRolloverEnabled(false);
        btnHaab.setVerifyInputWhenFocusTarget(false);
        btnHaab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHaabMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHaabMouseEntered(evt);
            }
        });
        btnHaab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaabActionPerformed(evt);
            }
        });

        panelC3.setBackground(new java.awt.Color(39, 232, 232));
        panelC3.setForeground(new java.awt.Color(58, 254, 243));
        panelC3.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHaab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelC3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnHaab, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setOpaque(false);

        btnRuedaCalen.setBackground(new java.awt.Color(204, 204, 204));
        btnRuedaCalen.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnRuedaCalen.setForeground(new java.awt.Color(254, 254, 254));
        btnRuedaCalen.setText("Rueda Calendarica");
        btnRuedaCalen.setBorderPainted(false);
        btnRuedaCalen.setContentAreaFilled(false);
        btnRuedaCalen.setRolloverEnabled(false);
        btnRuedaCalen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRuedaCalenMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRuedaCalenMouseEntered(evt);
            }
        });
        btnRuedaCalen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuedaCalenActionPerformed(evt);
            }
        });

        panelC4.setBackground(new java.awt.Color(39, 232, 232));
        panelC4.setForeground(new java.awt.Color(58, 254, 243));
        panelC4.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRuedaCalen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelC4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnRuedaCalen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelC4, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE))
        );

        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setOpaque(false);

        btnLinea.setBackground(new java.awt.Color(204, 204, 204));
        btnLinea.setFont(new java.awt.Font("Waree", 1, 11)); // NOI18N
        btnLinea.setForeground(new java.awt.Color(254, 254, 254));
        btnLinea.setText("Linea de Tiempo");
        btnLinea.setBorderPainted(false);
        btnLinea.setContentAreaFilled(false);
        btnLinea.setRolloverEnabled(false);
        btnLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLineaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLineaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLineaMouseEntered(evt);
            }
        });
        btnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(39, 232, 232));
        jSeparator1.setForeground(new java.awt.Color(58, 254, 243));
        jSeparator1.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        CalendarioMayaBTN.setBackground(new java.awt.Color(204, 204, 204));
        CalendarioMayaBTN.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        CalendarioMayaBTN.setForeground(new java.awt.Color(254, 254, 254));
        CalendarioMayaBTN.setText("Cerrar Sesion");
        CalendarioMayaBTN.setBorderPainted(false);
        CalendarioMayaBTN.setContentAreaFilled(false);
        CalendarioMayaBTN.setDefaultCapable(false);
        CalendarioMayaBTN.setRolloverEnabled(false);
        CalendarioMayaBTN.setVerifyInputWhenFocusTarget(false);
        CalendarioMayaBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CalendarioMayaBTNMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CalendarioMayaBTNMouseEntered(evt);
            }
        });
        CalendarioMayaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalendarioMayaBTNActionPerformed(evt);
            }
        });

        panelC1.setBackground(new java.awt.Color(39, 232, 232));
        panelC1.setForeground(new java.awt.Color(58, 254, 243));
        panelC1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalendarioMayaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
            .addComponent(panelC1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CalendarioMayaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setOpaque(false);

        btnNahuales.setBackground(new java.awt.Color(204, 204, 204));
        btnNahuales.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnNahuales.setForeground(new java.awt.Color(254, 254, 254));
        btnNahuales.setText("Nahuales");
        btnNahuales.setBorderPainted(false);
        btnNahuales.setContentAreaFilled(false);
        btnNahuales.setRequestFocusEnabled(false);
        btnNahuales.setRolloverEnabled(false);
        btnNahuales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNahualesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNahualesMouseEntered(evt);
            }
        });
        btnNahuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNahualesActionPerformed(evt);
            }
        });

        panelC5.setBackground(new java.awt.Color(39, 232, 232));
        panelC5.setForeground(new java.awt.Color(58, 254, 243));
        panelC5.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelC5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNahuales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnNahuales, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelC5))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFechas.setBackground(new java.awt.Color(1, 1, 1));

        jLabel2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("LA FECHA DE HOY ES:");

        jLabel5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Calendario Cholq'ij:");

        jLabel3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Calendario Haab:");

        lblFechaCholquij.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        lblFechaCholquij.setForeground(new java.awt.Color(254, 254, 254));
        lblFechaCholquij.setText("fecha");

        lblFechaHaab.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        lblFechaHaab.setForeground(new java.awt.Color(254, 254, 254));
        lblFechaHaab.setText("fecha2");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("BIENVENIDO AL TIEMPO MAYA");

        javax.swing.GroupLayout pnlFechasLayout = new javax.swing.GroupLayout(pnlFechas);
        pnlFechas.setLayout(pnlFechasLayout);
        pnlFechasLayout.setHorizontalGroup(
            pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechasLayout.createSequentialGroup()
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFechasLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaHaab)
                            .addComponent(lblFechaCholquij)))
                    .addGroup(pnlFechasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlFechasLayout.setVerticalGroup(
            pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblFechaCholquij))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblFechaHaab))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 997, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(pnlFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(pnlFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setBackground() {
        
        JLabel backgroundLbl = new JLabel();
        backgroundLbl.setSize(996, 559);
        backgroundLbl.setLocation(0, 0);
        backgroundLbl.setIcon(BG);
        this.add(backgroundLbl);
        backgroundLbl.setVisible(true);

    }
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed

    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        //cambiar el parametro nombre por el indicado
        Usuario user2 = info.buscarDatos(user.getUsername());
        if(user2 != null){
            FramePerfil perfil = new FramePerfil(null, true, user);
            perfil.setVisible(true);
        }
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnCholqijMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCholqijMouseEntered
        panelC2.setVisible(true);
    }//GEN-LAST:event_btnCholqijMouseEntered

    private void btnCholqijMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCholqijMouseExited
        panelC2.setVisible(false);
    }//GEN-LAST:event_btnCholqijMouseExited

    private void btnCholqijMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCholqijMouseClicked
        try {
            // TODO code application logic here
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "No se encuentra el estilo, por lo tanto se utlizara por defecto...");
        }
        FrameCalendario calendarioCholquij = new FrameCalendario();
        calendarioCholquij.setVisible(true);
    }//GEN-LAST:event_btnCholqijMouseClicked

    private void CalendarioMayaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalendarioMayaBTNActionPerformed
        archivoLogin.escribirArchivo(null);
        System.exit(0);
    }//GEN-LAST:event_CalendarioMayaBTNActionPerformed

    private void btnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaActionPerformed
        LineaDeTiempo linea = new LineaDeTiempo(user);
        linea.setVisible(true);
    }//GEN-LAST:event_btnLineaActionPerformed

    private void btnLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLineaMouseClicked
   
    }//GEN-LAST:event_btnLineaMouseClicked

    private void btnNahualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNahualesActionPerformed
        VentanaInfoNahuales ventanaInfoNahuales = new VentanaInfoNahuales();
        ventanaInfoNahuales.setVisible(true);
    }//GEN-LAST:event_btnNahualesActionPerformed

    private void btnHaabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHaabMouseEntered
        panelC3.setVisible(true);
    }//GEN-LAST:event_btnHaabMouseEntered

    private void btnHaabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHaabMouseExited
        panelC3.setVisible(false);
    }//GEN-LAST:event_btnHaabMouseExited

    private void btnRuedaCalenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuedaCalenMouseEntered
        panelC4.setVisible(true);
    }//GEN-LAST:event_btnRuedaCalenMouseEntered

    private void btnRuedaCalenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuedaCalenMouseExited
        panelC4.setVisible(false);
    }//GEN-LAST:event_btnRuedaCalenMouseExited

    private void btnNahualesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNahualesMouseEntered
        panelC5.setVisible(true);
    }//GEN-LAST:event_btnNahualesMouseEntered

    private void btnNahualesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNahualesMouseExited
        panelC5.setVisible(false);
    }//GEN-LAST:event_btnNahualesMouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
         
    }//GEN-LAST:event_jPanel1MouseExited

    private void CalendarioMayaBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalendarioMayaBTNMouseEntered
        panelC1.setVisible(true);
    }//GEN-LAST:event_CalendarioMayaBTNMouseEntered

    private void CalendarioMayaBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalendarioMayaBTNMouseExited
        panelC1.setVisible(false);
    }//GEN-LAST:event_CalendarioMayaBTNMouseExited

    private void btnLineaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLineaMouseEntered
        jSeparator1.setVisible(true);
    }//GEN-LAST:event_btnLineaMouseEntered

    private void btnLineaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLineaMouseExited
        jSeparator1.setVisible(false);
    }//GEN-LAST:event_btnLineaMouseExited

    private void btnCholqijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCholqijActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCholqijActionPerformed

    private void btnHaabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaabActionPerformed
        CalendarioHaab cal = new CalendarioHaab();
        cal.setVisible(true);
    }//GEN-LAST:event_btnHaabActionPerformed

    private void btnRuedaCalenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuedaCalenActionPerformed
        RuedaCalendarica rueda = new RuedaCalendarica();
        rueda.setVisible(true);
    }//GEN-LAST:event_btnRuedaCalenActionPerformed

    public void escribirFecha() {
        Calendar fecha = new GregorianCalendar();
        System.out.println(fechaStr);
        FechaHaab fechaHaab = new FechaHaab();
        FechaCholqij fechaCholquij = new FechaCholqij();
        lblFechaHaab.setText(fechaHaab.obtenerFecha(fechaStr));
        lblFechaCholquij.setText(fechaCholquij.fechaEscritaCholquij(fecha.getTime().getTime()));
    }
    
    private void designe(){
        panelC1.setVisible(false);
        panelC2.setVisible(false);
        panelC3.setVisible(false);
        panelC4.setVisible(false);
        panelC5.setVisible(false);
        jSeparator1.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalendarioMayaBTN;
    private javax.swing.JButton btnCholqij;
    private javax.swing.JButton btnHaab;
    private javax.swing.JButton btnLinea;
    private javax.swing.JButton btnNahuales;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnRuedaCalen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFechaCholquij;
    private javax.swing.JLabel lblFechaHaab;
    private javax.swing.JSeparator panelC1;
    private javax.swing.JSeparator panelC2;
    private javax.swing.JSeparator panelC3;
    private javax.swing.JSeparator panelC4;
    private javax.swing.JSeparator panelC5;
    private javax.swing.JPanel pnlFechas;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
